# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Lane for tests"
  lane :tests do
      scan(
          scheme: "ToDoList",
          devices: ["iPhone Xʀ"],
          result_bundle: true,
          derived_data_path: "~/Library/Developer/Xcode/DerivedData"
      )
  end

  desc "Lane for taking screenshots"
  lane :screenshots do
    capture_screenshots
  end

  desc "Lane for incrementing build number"
  lane :build_number do
    increment_build_number
  end

  desc "Test app, take screenshot, build"
  lane :build_beta do
    tests
    screenshots
    build_number
  end
end
